import "./globals.css";
import type { Metadata } from "next";
import { AppProviders } from "~/client/providers/AppProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex overflow-hidden w-full h-full absolute justify-center items-center">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
