import "./globals.css";
import type { Metadata } from "next";
import { WalletProvider } from "~/client/providers/WalletProvider";
import { QueryProvider } from "./client/providers/QueryProvider";
import { TransactionProvider } from "./client/providers/TransactionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex overflow-hidden w-full h-full absolute justify-center items-center">
        <WalletProvider>
          <TransactionProvider>
            <QueryProvider>{children}</QueryProvider>
          </TransactionProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
